spring:
    jpa:
        hibernate:
            ddl-auto: create
    data:
        elasticsearch:
            cluster-name:
            cluster-nodes:
            properties:
                path:
                    logs: target/elasticsearch/log
                    data: target/elasticsearch/data

logging:
    level:
        org.hibernate.SQL: debug
        gov.kktcmeb.security.kktcmebsecurityacl: debug
